config/routes.rb
Rails.application.routes.draw do
  get 'reviews/show'
  get 'reviews/new'
  get 'reviews/edit'
  resources :professors do
    resources :reviews
  end
  root 'home#index'
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/professor.rb
class Professor
  include Mongoid::Document
  include Mongoid::Timestamps
  include Mongoid::Search

  field :first_name, type: String
  field :last_name, type: String
  field :department, type: String

  field :helpfulness, type: Float, default: 0.0
  field :pedagogy, type: Float, default: 0.0
  field :easiness, type: Float, default: 0.0
  field :overall, type: Float, default: 0.0

  index({ first_name: 1, last_name: 1 })

  has_many :reviews, before_add: :calculate_ratings

  validates_presence_of :first_name, :last_name

  search_in :first_name, :last_name
  

  def full_name
      [self.first_name, self.last_name] .join(" ")
  end

  def self.search query
      full_text_search(query, match: :all)
  end


  protected
  def calculate_ratings(review)
    reviews_count = self.reviews.count
    if reviews_count <= 0
      self.helpfulness = review.helpfulness
      self.pedagogy = review.pedagogy
      self.easiness = review.easiness
    else
      self.helpfulness = (helpfulness * reviews.length + review.helpfulness) / (reviews.length + 1)
      self.pedagogy = (pedagogy * reviews.length + review.pedagogy) / (reviews.length + 1)
      self.easiness = (easiness * reviews.length + review.easiness) / (reviews.length + 1)
    end
    self.overall = (pedagogy + easiness + helpfulness) / 3.0
    self.save
  end



end

app/models/review.rb
class Review
  include Mongoid::Document
  include Mongoid::Timestamps

  field :comment, type: String
  field :helpfulness, type: Integer
  field :pedagogy, type: Integer
  field :easiness, type: Integer
  field :overall, type: Float
  field :class_taken, type: String
  field :year, type: Integer
  field :attendance, type: String

  validates_presence_of :helpfulness, :pedagogy, :easiness
  validates :helpfulness, inclusion: { in: (1..5) }
  validates :pedagogy, inclusion: { in: (1..5) }
  validates :easiness, inclusion: { in: (1..5) }
  validate :year_within_range

  belongs_to :professor, index: true

  before_save :assign_overall

  protected
  def year_within_range
    errors.add(:year, "is not within range") unless (1970..Date.current.year).include? year
  end

  def assign_overall
    self.overall = (pedagogy + easiness + helpfulness) / 3.0
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
    layout 'home'
  def index
  end
end

app/controllers/professors_controller.rb
class ProfessorsController < ApplicationController
  before_action :set_professor, only: [:show, :edit, :update, :destroy]
  def index
      if not params[:q].blank?
	  @professors = Professor.search(params[:q])
      else
	  @professors = Professor.all
      end
      if not params[:order].blank?
	if params[:order] == "rating"
	    order = "overall"  
	else
	    order = "last_name"
	end
      end

      if not params[:sort].blank?
	sort = params[:sort]
      else
	  sort = "DESC"
      end
	  @professors = @professors.order_by(order + " " + sort)
  end

  def show
    
  end

  def edit

  end

  def new
      @professor = Professor.new
  end

  def create
      @professor = Professor.new(professor_params)
      if @professor.save
	  redirect_to @professor, notice: "Professor has been added"
      else
	  render :new
      end
  end

  def update
      if @professor.update(professor_params)
	  redirect_to @professor, notice: "Professor updated"
      else
	  render :edit
      end
  end

  def destroy
      @professor.destroy
      redirect_to professors_path, notice: "Professor deleted"
  end
  
  private 
  def set_professor
      @professor = Professor.find(params[:id])
  end

  def professor_params
      params.require(:professor).permit(:first_name, :last_name)
  end
end

app/controllers/reviews_controller.rb
class ReviewsController < ApplicationController
  before_action :set_review, only: [:show, :edit, :update, :destroy]
  before_action :set_professor, only: [:new, :index, :set_review, :create]

  def index
    @reviews = @professor.reviews
  end
  def show

  end

  def new
      @review = Review.new
  end

  def edit

  end

  def create
      @review = Review.new(review_params)
      @professor.reviews << @review
      
      if @review.save
	redirect_to @professor, notice: "Review was successfully submitted"
      else
	render :new
      end
  end

  def update
    if @review.update(review_params)
	redirect_to @professor, notice: "Review was successfully updated"
    else
	render :edit
    end
  end

  def destroy
    @review.destroy
    redirect_to @professor, notice: "Review deleted"
  end

  private
  def set_review
      @review = professor.reviews.find(params[:id])
  end

  def set_professor
      @professor = Professor.find(params[:professor_id])
  end

  def review_params
      params.require(:review).permit(:class_taken, :year, :helpfulness, :pedagogy, :easiness, :comment)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
    def display_name professor
	[professor.last_name, professor.first_name].join(", ")
    end

    def get_rating_color value
	if value <= 2.0
	    color = "is-danger"
	elsif value <= 3
	    color = "is-warning"
	else
	    color = "is-success"
	end
	color
    end

    def display_float float
	number_with_precision(float, precision: 2)
    end

    def get_rating_name value
	if value <= 1
	    word = "Very poor"
	elsif value <= 2
	    word = "Poor"
	elsif value <= 3
	    word = "Fair"
	elsif value <= 4
	    word = "Good"
	else
	    word = "Excellent"
	end
	word
    end
end

app/helpers/home_helper.rb
module HomeHelper
end

app/helpers/professors_helper.rb
module ProfessorsHelper
end

app/helpers/reviews_helper.rb
module ReviewsHelper
end

app/views/home/index.html.erb
<section class="hero is-primary is-medium header">
    <div class = "hero-head" style = "padding-top:40px;">
	<h1 class = "title has-text-centered is-1">
	    Hello, UP Students!
	</h1>
	<h2 class = "subtitle has-text-centered is-2">Welcome to the new RUPP!</h2>
    </div>
    <div class="hero-body">
	<div class="container">
	    <div class="columns">
		<div class="column is-two-thirds is-centered" style= "margin: auto;">
		    <div class="notification is-white">
			<h2 class = "title has-text-centered has-text-black">Rate your UP Professors</h2>
			<h3 class = "subtitle has-text-centered has-text-black">Search for professors here</h3>
			<%= form_with(url: professors_path, method: :get, local: true) do |f| %>
			    <p class = "control has-icons-left">
				<%= f.text_field :q, class: "input is-medium", placeholder: "Search" %>
				<span class="icon is-small is-left">
				    <%= fa_icon "search" %>
				</span>
			    </p>
			<% end %>
		    </div>
		</div>
	    </div>
	</div>
    </div>
</section>
<section class = "section">
    <div class = "columns">
	<div class = "column is-one-third">
	    <div class = "card is-shadowless has-text-centered">
		<div class = "card-image">
		    <span class = "icon has-text-danger is-size-1">
			<%= fa_icon "heart" %>
		    </span>
		</div>
		<div class = "card-content">
			<h3 class = "title">
			    For UP Students By UP Students 
			</h3>
			<p class = "subtitle">
			    RUPP is still created and maintained by UP Students.
			    The site is  unaffiliated with any college 
			    departments or organizations.
			</p>
			<p class = "subtitle">
			    Anything that happens on this site is not biased towards any student body nor is it
			    politically-driven by any group or organization. 
			</p>
		</div>
	    </div>
	</div>
	<div class = "column is-one-third">
	    <div class = "card is-shadowless has-text-centered">
		<div class = "card-image">
		    <span class = "icon has-text-warning is-size-1 ">
			<%= fa_icon "shield" %>
		    </span>
		</div>
		<div class = "card-content">
			<h3 class = "title">
			    Secure and Anonymous
			</h3>
			<p class = "subtitle">
			    You are not required to submit any data that may be used to trace back to you. Every review you place is untraceable and anonymous.
			</p>
			<p class = "subtitle">
			    So don't worry about professors finding out, because it's impossible for them to know who you are.
			</p>
		</div> 
	    </div> 
	</div>
	<div class = "column is-one-third">
	    <div class = "card is-shadowless has-text-centered">
		<figure class = "card-image">
		    <span class = "icon has-text-success is-size-1">
			<%= fa_icon "plus" %>
		    </span>
		</figure>
		<div class = "card-content">
			<h3 class = "title">
			    Constantly Improving
			</h3>
			<p class = "subtitle">
			    This site is constantly approving and accepting feedback. That way we can make sure that students are getting the best experience possible
			</p>
			<p class = "subtitle">
			    Although the site looks and feels new, we still keep all the old reviews on here. So don't worry about losing them!
			</p>
		</div>
	    </div>
	</div>
    </div>
</section>

<section class = "section has-text-centered">
    <span class = "is-size-3">RUPP is under new management, but we are still upholding RUPP's core values.</span>
</section>

app/views/layouts/_imports.html.erb
  <head>
    <title>Rate Your UP Professors</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

app/views/layouts/application.html.erb
<!DOCTYPE html>

<html>
    <%= render "layouts/imports"%>
  <body>
      <nav class="navbar is-primary" role="navigation" aria-label="main navigation">
  <div class="navbar-brand">
    <%= link_to "Rate your UP Professor", root_path, class: "navbar-item" %>

    <a role="button" class="navbar-burger" aria-label="menu" aria-expanded="false">
      <span aria-hidden="true"></span>
      <span aria-hidden="true"></span>
      <span aria-hidden="true"></span>
    </a>
  </div>
  <div class="navbar-menu">
      <div class="navbar-end">
	  <div class="navbar-item">
	  <%= form_with(url: professors_path, method: :get, local: true) do |f| %>
	      <div class = "field has-addons">
		  <div class = "control has-icons-left">
		      <%= f.text_field :q, class: "input is-medium", placeholder: "Search" %>
		      <span class="icon is-small is-left">
			  <%= fa_icon "search" %>
		      </span>
		  </div>
		  <div class="control">
		      <%= f.submit "Search", class: "button is-info is-medium" %>
		  </div>
	      </div>
	  <% end %>
	  </div>
      </div>
  </div>
</nav>
    <%= yield %>
  </body>
</html>

app/views/layouts/hidden.html.erb
<!DOCTYPE html>
<html>
    <%= render "layouts/imports"%>
  <body>
    <%= yield %>
  </body>
</html>

app/views/layouts/home.html.erb
<!DOCTYPE html>
<html>
    <%= render "layouts/imports"%>
  <body>
	  <!--
      <section class="section has-background-primary">
      <nav class="level "> <div class="level-item has-text-centered"> <%= link_to "Professors", professors_path , class: ""%> </div> <div class="level-item has-text-centered"> Rate your UP Professors
	  </div>
	  <div class="level-item has-text-centered">
	      <%= link_to "Contact Us", "#"%>
	  </div>
      </nav>
</section>
  -->
    <%= yield %>
  </body>
</html>

app/views/professors/_form.html.erb
<%= form_with(model: @professor, local:true) do |f| %>
    <% @professor.errors.full_messages.each do |m|%>
	<span><%= m %></span>
    <% end %>

    <%= f.label :first_name %>
    <%= f.text_field :first_name %>
    <%= f.label :last_name %>
    <%= f.text_field :last_name%>

    <%= f.submit %>
<% end %>

app/views/professors/_professor.html.erb
<div class="box">
    <article class="media">
	<div class="media-left">
	    <% color = get_rating_color professor.overall %>
	    <span class="<%= "tag is-large " + color if not color.blank? %>" >
		<%= display_float professor.overall %>
		<span class= "is-size-7"> / 5.0</span>
	    </span>
	</div>
	<div class="media-content">
	    <div class="content">
		<h3 class="title"><%= link_to display_name(professor), professor, class: "has-text-primary" %></h3>
		<p class = "subtitle">
		    <small>
			<span>Helpfulness: <%= display_float professor.helpfulness %> </span>
			<span class= "is-size-7"> / 5.00</span>
			<br>
			<span>Pedagogy: <%= display_float professor.pedagogy %> </span>
			<span class= "is-size-7"> / 5.00</span>
			<br>
			<span>Easiness: <%= display_float professor.easiness%> </span>
			<span class= "is-size-7"> / 5.00</span>
		    </small>
		</p>
	    </div>
	</div>
    </article>
</div>

app/views/professors/index.html.erb
<section class="section has-background-light">
    <div class="container">
	<div class="box">
	    <%= form_for "", method: :get, local: true do |f| %>
		<div class="field has-addons">
		    <div class = "control has-icons-left is-expanded">
			<%= f.text_field :q, class: "input is-medium", placeholder: "Search For Professors", value: params[:q] %>
			<span class="icon is-small is-left">
			    <%= fa_icon "search" %>
			</span>
		    </div>
		    <div class="control">
			<%= f.submit "Search", class: "button is-info is-medium" %>
		    </div>
		</div>
	    <% end %>

	</div>
	<div class="level">
	    <div class="level-left">
		<%= form_tag '', method: :get do %>
		    <div class="level-item">
			<%= label_tag :order, "Order by", class: "label" %>
			<div class="select">

			    <%= select_tag :order, options_for_select([["Alphabetical A-Z", "alpha"],["Overall Rating", "rating"]], selected: params[:order]), {class: "select", onchange: "this.form.submit();"} %>

			</div>
		    </div>
		    <div class="level-item">
			<%= label_tag :sort, "Sort", class: "label" %>
			<div class="select">

			    <%= select_tag :sort, options_for_select([["Ascending", "ASC"],["Descending", "DESC"]], selected: params[:sort]), {class: "select", onchange: "this.form.submit();"} %>

			</div>
		    </div>
		<% end %>
	    </div>
	</div>
	<%= render @professors %>
    </div>
</section>

app/views/professors/show.html.erb
<% color = get_rating_color @professor.overall %>
<section class="<%= "hero is-bold " + color if not color.blank? %>">
    <div class="hero-body">
	<div class="container">
	    <h1 class="title is-1 has-text-centered"><%=display_name @professor %></h1>
	    </h2>
	</div>
    </div>
    <div class="hero-body">
	<div class="container">
	    <h1 class="title is-2 has-text-centered">Overall: <%= display_float @professor.overall%></h1>
	    <h2 class="subtitle is-3 has-text-centered"><%= get_rating_name @professor.overall %></h2>
	</div>
    </div>
</section>
<section class="section">
	    <nav class="level">
		<div class="level-item has-text-centered">
		    <div>
			<p class = "title">Pedagogy</p>
			<%= display_float @professor.pedagogy %><br>
			<%= render "shared/progress_bar", value: @professor.pedagogy %>
			<%= get_rating_name @professor.pedagogy %>
		    </div>
		</div>
		<div class="level-item has-text-centered">
		    <div>
			<p class = "title">Helpfulness</p>
			<%= display_float @professor.helpfulness %>
			<%= render "shared/progress_bar", value: @professor.helpfulness %>
			<%= get_rating_name @professor.helpfulness%>
		    </div>
		</div>
		<div class="level-item has-text-centered">
		    <div>
			<p class = "title">Easiness</p>
		    <%= display_float @professor.easiness%>
			<%= render "shared/progress_bar", value: @professor.easiness %>
			<%= get_rating_name @professor.easiness %>
		    </div>
		</div>
	    </nav>

</section>

<section class="section has-background-light">
    <div class="container">
    <h3 class="title has-text-centered">Reviews</h3>
    <p class = "subtitle has-text-centered"> <%= link_to "Submit a Review", new_professor_review_path(@professor) %> </p>
    <% @professor.reviews.each do |review| %>
	<%= render "reviews/review", review: review %>
    <% end %></div>
    <br>
    <% if not @professor.reviews.any? %>
	<h3 class = "subtitle is-5 has-text-centered">No reviews yet. Click <%= link_to "here", new_professor_review_path(@professor) %> to write one </h3>
    <% end %>
</section>

app/views/reviews/_form.html.erb
<%= form_for([@professor, @review], local: true, url: professor_reviews_path) do |f| %>

    <% @review.errors.full_messages.each do |m|%>
	<span><%= m %></span>
    <% end %>

    <div class=  "field is-grouped">
	<%= f.label :helpfulness , class: "label is-extended"%><br>
	<div class = "control">
	    <div class = "select">
		<%= f.select :helpfulness, options_for_select([1,2,3,4,5]) %>
	    </div>
	</div>

	<%= f.label :pedagogy , class: "label"%>
	<div class = "control">
	    <div class = "select">
		<%= f.select :pedagogy, options_for_select([1,2,3,4,5]) %>
	    </div>
	</div>

	<%= f.label :easiness , class: "label"%>
	<div class = "control">
	    <div class = "select">
		<%= f.select :easiness, options_for_select([1,2,3,4,5]) %>
	    </div>
	</div>
    </div>

    <div class=  "field">
	<%= f.label :comment , class: "label"%>
	<div class = "control">
	    <%= f.text_area :comment, class:'textarea' %>
	</div>
    </div>
    <div class=  "field">
	<%= f.label :class_taken, "Class Taken", class: "label"%>
	<div class = "control">
	    <%= f.text_field :class_taken, class: "input" %>
	</div>
    </div>

    <div class=  "field">
	<%= f.label :year, "Year Taken" , class: "label"%>
	<div class = "control">
	    <%= f.text_field :year, value: Time.current.year , class: "input"%>
	</div>
    </div>

    <div class=  "field">
	<%= f.submit "Submit Review", class: "button is-info" %>
    </div>
<% end %>

app/views/reviews/_review.html.erb
<div class="box">
    <article class="media">
	<div class="media-left">
	    <strong>Overall: <%= display_float review.overall %></strong><br>
	    <%= render "shared/progress_bar", value: review.overall%>
	    <hr>
	    Pedagogy: <%= review.pedagogy %><br>
	    <%= render "shared/progress_bar", value: review.pedagogy%>
	    Helpfulness: <%= review.helpfulness %><br>
	    <%= render "shared/progress_bar", value: review.helpfulness %>
	    Easiness: <%= review.easiness %>
	    <%= render "shared/progress_bar", value: review.easiness%>
	</div>
    <div class="media-content">
	<em>
	<strong>Class:</strong> <%= review.class_taken %><br>
	<strong>Year:</strong> <%= review.year %><br> <br>
	</em>
	<p><%= review.comment %></p>
    </div>
    </article>
</div>

app/views/reviews/edit.html.erb
<h1>Reviews#edit</h1>
<p>Find me in app/views/reviews/edit.html.erb</p>

app/views/reviews/index.html.erb
<%= render @reviews %>

app/views/reviews/new.html.erb
<div class="has-text-centered">
    <div class="box">
	<h3 class = "title has-text-primary"><%= display_name @professor %></h3>
	<p class = "subtitle"><strong>Overall Score:</strong> <%= display_float @professor.overall %></p>
    </div>
</div>
<section class="section">
    <div class="container">
<%= render "form" %>
    </div>
</section>

app/views/reviews/show.html.erb
<%= @review.class_taken%>
<%= @review.year %>

<%= @review.helpfulness %>
<%= @review.pedagogy%>
<%= @review.easiness%>

<%= @review.comment%>

app/views/shared/_progress_bar.html.erb
<% color = get_rating_color value %>
<progress class = "<%= "progress " + color %>" value = <%= value %> max = 5><%= value %></progress>